/**
 * Evidence freeze CLI (M25).
 *
 *   pnpm freeze:check   verify the corpus against the frozen claims (runs in CI)
 *   pnpm freeze:write   re-freeze — owner action, reviewed in the diff
 *   pnpm freeze:ledger  regenerate docs/evidence/CLAIM-LEDGER.md
 *
 * Verification is the default because the freeze is only worth having if the
 * build refuses to pass when a public claim moves.
 */

import { writeFileSync, existsSync, readFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { loadEvidenceGraph } from "../src/lib/evidence/load-graph";
import {
  assertStrengthCoversAllStates,
  buildClaimSet,
  buildFreezeManifest,
  ownerOnlyClaims,
  verifyFreeze,
  type Claim,
  type FreezeManifest,
  type FreezeStatus,
} from "../src/lib/freeze";

const FREEZE_PATH = join(process.cwd(), "content", "evidence", "freeze.json");
const LEDGER_PATH = join(process.cwd(), "docs", "evidence", "CLAIM-LEDGER.md");

function readManifest(): FreezeManifest {
  if (!existsSync(FREEZE_PATH)) {
    console.error(`No freeze manifest at ${FREEZE_PATH} — run \`pnpm freeze:write\`.`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(FREEZE_PATH, "utf8")) as FreezeManifest;
}

function writeManifest(claims: Claim[], status: FreezeStatus) {
  const previous = existsSync(FREEZE_PATH)
    ? (JSON.parse(readFileSync(FREEZE_PATH, "utf8")) as FreezeManifest)
    : null;

  const manifest = buildFreezeManifest(claims, {
    status,
    frozenAt: new Date().toISOString().slice(0, 10),
  });
  // Re-freezing must not erase the history of what was changed and why.
  manifest.changeControl = previous?.changeControl ?? [];

  writeFileSync(FREEZE_PATH, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  console.log(
    `Froze ${claims.length} claims (${manifest.corpusDigest}) with status ${status}.`,
  );
}

function table(rows: string[][]): string {
  const header = `| ${rows[0].join(" | ")} |`;
  const rule = `|${rows[0].map(() => "---").join("|")}|`;
  const body = rows.slice(1).map((row) => `| ${row.join(" | ")} |`);
  return [header, rule, ...body].join("\n");
}

function escapePipes(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function writeLedger(claims: Claim[], manifest: FreezeManifest) {
  const byKind = new Map<string, Claim[]>();
  for (const claim of claims) {
    byKind.set(claim.kind, [...(byKind.get(claim.kind) ?? []), claim]);
  }

  const ownerOnly = ownerOnlyClaims(claims).filter(
    (claim) => claim.kind !== "exclusion" && claim.kind !== "corpus",
  );

  const sections = [...byKind.entries()].map(([kind, kindClaims]) => {
    const rows = [
      ["Claim", "State", "Where is the evidence?"],
      ...kindClaims.map((claim) => [
        escapePipes(claim.statement),
        claim.evidenceState ?? "—",
        claim.evidence.length > 0
          ? claim.evidence.map((id) => `\`${id}\``).join("<br>")
          : "**owner's word only**",
      ]),
    ];
    return `### ${kind} (${kindClaims.length})\n\n${table(rows)}`;
  });

  const body = `# Claim ledger

<!-- Generated by \`pnpm freeze:ledger\`. Do not edit by hand. -->

Every claim this portfolio makes in public, and the evidence that answers
**"where is the evidence?"**. Generated from the Evidence Graph, so it cannot drift
from what the site actually renders.

**Freeze status:** ${manifest.status}
**Frozen at:** ${manifest.frozenAt}
**Corpus digest:** \`${manifest.corpusDigest}\`
**Claims:** ${claims.length}

A claim marked **owner's word only** is not weaker because it is dishonest — it is
professional truth that cannot be made public (proprietary employer code) or that
rests on a document rather than a repository. The site labels these
\`OWNER_CONFIRMED_PROFESSIONAL\` or \`RESUME_DOCUMENTED\` and never presents them as
verifiable.

## Claims needing owner confirmation before launch (${ownerOnly.length})

These are the facts no validator can check. ${"They are frozen as written; correcting one is a change-control entry, not a silent edit."}

${table([
  ["Claim", "State"],
  ...ownerOnly.map((claim) => [escapePipes(claim.statement), claim.evidenceState ?? "—"]),
])}

## All claims by kind

${sections.join("\n\n")}
`;

  mkdirSync(dirname(LEDGER_PATH), { recursive: true });
  writeFileSync(LEDGER_PATH, body, "utf8");
  console.log(`Wrote ${LEDGER_PATH} (${claims.length} claims).`);
}

function main() {
  assertStrengthCoversAllStates();

  const graph = loadEvidenceGraph();
  const claims = buildClaimSet(graph);
  const mode = process.argv[2] ?? "--check";

  const ids = new Set<string>();
  for (const claim of claims) {
    if (ids.has(claim.id)) {
      console.error(`Duplicate claim id: ${claim.id}`);
      process.exit(1);
    }
    ids.add(claim.id);
  }

  if (mode === "--write") {
    const status = process.argv.includes("--confirmed")
      ? "OWNER_CONFIRMED"
      : "PENDING_OWNER_CONFIRMATION";
    writeManifest(claims, status);
    writeLedger(claims, readManifest());
    return;
  }

  if (mode === "--ledger") {
    writeLedger(claims, readManifest());
    return;
  }

  const manifest = readManifest();
  const result = verifyFreeze(claims, manifest);

  for (const note of result.accepted) console.log(`  recorded change: ${note}`);

  if (!result.ok) {
    console.error(
      `\nEvidence freeze violated — ${result.violations.length} claim(s) moved without change control:\n`,
    );
    for (const violation of result.violations) {
      console.error(`  [${violation.kind}] ${violation.claimId}: ${violation.detail}`);
    }
    console.error(
      "\nWeaken or restore the claim, or record the change in content/evidence/freeze.json.",
    );
    process.exit(1);
  }

  console.log(
    `Evidence freeze OK — ${claims.length} claims match ${manifest.corpusDigest} (${manifest.status}).`,
  );
}

main();
